version: '3.0'

services:
  mongo_db:
    image: mongo
    container_name: mongo_db_players
    ports:
      - 27017:27017
    volumes:
      - mongoplayers:/data/configdb
      - mongoplayers:/data/db

volumes:
  mongoplayers: {}
